#!/usr/bin/env node
/*▄────────▄
  █        █
  █  Ядро  █
  █        █
  ▀────────▀*/
require('./lib/core/core');

/*▄───────▄
  █       █
  █  MVC  █
  █       █
  ▀───────▀*/
// Коллекция точек входа
require('./lib/entrypoints/entrypointInstall');

/*▄───────────────▄
  █               █
  █  Точка входа  █
  █               █
  ▀───────────────▀*/
entrypoint = (...args) => {
    if (args[0] == 'i') {
        $.entrypoint.Install(...args.slice(1))
    }
};
